### ISSUE TITLE
Crash while trying to parse WatchKit app storyboard

### ISSUE THREAD

**Issue by mgrebenets** [IBDecodable/IBLinter#104] opened 2019-05-30 01:02 UTC
Hi there

We've got one WatchKit app storyboard, that seems to cause trouble for IBLinter and causes it to crash.

The error is this:

> Fatal error: parse error /path/to/project/WatchKitApp/Base.lproj/Interface.storyboard: XML Element Error: Incorrect key ["archive"]: file /Users/travis/build/IBDecodable/IBLinter/Sources/IBLinterKit/Validator.swift, line 36

The storyboard renders in Xcode properly, I've checked it with `xmllint` and it reported no errors.
I can't even find a key called "archived" inside storyboard XML file 🤔

not sure what's the root cause.

Out of curiosity, I've removed everything from the storyboard and only this was left:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<document type="com.apple.InterfaceBuilder.WatchKit.Storyboard" version="3.0" toolsVersion="14460.31" targetRuntime="watchKit" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" colorMatched="YES">

</document>
```

still causes the same crash.

**Comment by phimage** [comment] 2019-05-30 17:43
watch os are not supported but must be skipped
the expected error thrown by IBDecodable
https://github.com/IBDecodable/IBDecodable/blob/e9b642b6e8e1dc77ae9f139286197cd5bde754f0/Sources/Parsers/InterfaceBuilderParser.swift#L74

the decoding
https://github.com/IBDecodable/IBDecodable/blob/e9b642b6e8e1dc77ae9f139286197cd5bde754f0/Sources/Parsers/InterfaceBuilderParser.swift#L23

**Comment by mgrebenets** [comment] 2019-05-30 23:11
I see, so all IBLinter users should ignore WatchKit storyboards then...

Just curious, instead of crashing, could IBLinter display a warning saying "WatchKit storyboards are not supported" or just skip them silently?
I guess any kind of warning would be better than the crash.

I've spend some time digging into our WatchKit storyboard trying to understand where exactly it is broken.

**Comment by phimage** [comment] 2019-06-01 07:51
the issue is for any malformed xml as I see (like empty one from test)

We receive a not converted/catched IndexingError from XML decoding library
XML Element Error: Incorrect key ["archive"]

error thrown by
https://github.com/IBDecodable/IBDecodable/blob/e9b642b6e8e1dc77ae9f139286197cd5bde754f0/Sources/Parsers/InterfaceBuilderParser.swift#L67

**Comment by mgrebenets** [comment] 2019-06-02 04:40
The XML in question is WatchKit storyboard. I couldn’t paste the full version. Will try to create fresh WatchKit storyboard instead and see if it still causes same issue. 

Other than that the XML that I have renders properly in interface builder and lints fine with xmllint tool.

**Comment by phimage** [comment] 2019-06-02 18:12
I make I think the necessary change in IBDecodable project

A violation must be created from `Error.xmlError` and no more fatalError
when new version of IBDecodable will be integrated here

**Closed** 2019-06-03 09:59 UTC
Labels: bug

**Comment by mgrebenets** [comment] 2019-06-04 05:55
Tested just now, I get the warning now

> ... warning: Parse XML error XML Element Error: Incorrect key ["archive"]

Which is much better than a crash from before 👍
